In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('netflix_titles.csv.zip')

<h1>1. Knowing My data</h1>

In [4]:
data.shape

(8807, 12)

In [5]:
data.head(2)['cast'].values

<ArrowStringArray>
[nan, 'Ama Qamata, Khosi Ngema, Gail Mabalane, Thabang Molaba, Dillon Windvogel, Natasha Thahane, Arno Greeff, Xolile Tshabalala, Getmore Sithole, Cindy Mahlangu, Ryle De Morny, Greteli Fincham, Sello Maake Ka-Ncube, Odwa Gwanya, Mekaila Mathys, Sandi Schultz, Duane Williams, Shamilla Miller, Patrick Mofokeng']
Length: 2, dtype: str

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 3.9 MB

In [7]:
data.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [8]:
data.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [9]:
data.duplicated().sum()

np.int64(0)

In [10]:
data.corr(numeric_only=True)

              release_year
release_year           1.0

<h1>2. Univariate Analysis</h1>

In [11]:
# what columns we keep----> type, director, cast, country, rating, duration, listed_in, description, show_id, release_date

In [12]:
data = data[['title','type' , 'director','cast','country','rating','duration','listed_in','description','show_id','release_year']]

In [13]:
data.sample(5)

,title,type,director,cast,country,rating,duration,listed_in,description,show_id,release_year
130,Barbie Big City Big Dreams,Movie,Scott Pleydell-Pearce,"America Young, Amber May, Giselle Fernandez, A...",NaN,TV-Y,63 min,"Children & Family Movies, Music & Musicals",At a summer performing arts program in New Yor...,s131,2021
1214,Quiet,Movie,Luis Alejandro Pérez,"Max Salgado, René Miranda, Ignacia Uribe, Javi...",NaN,TV-MA,103 min,"Dramas, International Movies, Music & Musicals",The lives of three Chilean teenage misfits con...,s1215,2020
7534,My Dog is My Guide,Movie,Ismail Farouk,"Sameh Hussain, Hasan Abdulfattah, Sulayman Id,...",Egypt,TV-14,99 min,"Comedies, International Movies",Relocated to a new post and struggling to adju...,s7535,2013
5536,Frat Star,Movie,"Grant S. Johnson, Ippsie Jones","Connor Lawrence, Justin Mark, Cathryn Dylan, C...",United States,TV-MA,85 min,Comedies,A freshman uninterested in joining a fraternit...,s5537,2017
5158,Barbra: The Music ... The Mem'ries ... The Magic!,Movie,"Barbra Streisand, Jim Gable",Barbra Streisand,United States,TV-14,109 min,Music & Musicals,Iconic songstress Barbra Streisand culminates ...,s5159,2017

In [14]:
data.isnull().sum()

title              0
type               0
director        2634
cast             825
country          831
rating             4
duration           3
listed_in          0
description        0
show_id            0
release_year       0
dtype: int64

In [15]:
data = data.dropna().reset_index(drop=True)

In [16]:
data.isnull().sum()

title           0
type            0
director        0
cast            0
country         0
rating          0
duration        0
listed_in       0
description     0
show_id         0
release_year    0
dtype: int64

In [17]:
def convert(str):
  str = str.replace(" Movies", "")
  str = str.replace(" TV Shows", "")
  str = str.split(",")
  return str

In [18]:
data['listed_in'] = data['listed_in'].apply(convert)

In [19]:
data.head()

,title,type,director,cast,country,rating,duration,listed_in,description,show_id,release_year
0,Sankofa,Movie,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",TV-MA,125 min,"[Dramas, Independent, International]","On a photo shoot in Ghana, an American model s...",s8,1993
1,The Great British Baking Show,TV Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,TV-14,9 Seasons,"[British, Reality TV]",A talented batch of amateur bakers face off in...,s9,2021
2,The Starling,Movie,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,PG-13,104 min,"[Comedies, Dramas]",A woman adjusting to life after a loss contend...,s10,2021
3,Je Suis Karl,Movie,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic",TV-MA,127 min,"[Dramas, International]",After most of her family is murdered in a terr...,s13,2021
4,Jeans,Movie,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,TV-14,166 min,"[Comedies, International, Romantic]",When the father of the man she loves insists t...,s25,1998

In [20]:
def convertC(str):
  str = str.split(",")
  if len(str) >= 3:
    return str[:3]
  else:
    return str

In [21]:
data['cast'] = data['cast'].apply(convertC)

In [22]:
data['description'] = data['description'].apply(lambda x: x.split())

In [23]:
data['listed_in'] = data['listed_in'].apply(lambda x: [i.replace(" ", "") for i in x])
data['cast'] = data['cast'].apply(lambda x: [i.replace(" ", "") for i in x])
data['director'] = data['director'].apply(lambda x: ["".join(x)])

In [24]:
data['director'] = data['director'].apply(lambda x: [i.replace(" ", "") for i in x])

In [25]:
data['tags'] = data['director'] + data['cast'] + data['listed_in'] + data['description']

In [26]:
newdata = data[['title','show_id', 'type', 'country', 'rating', 'duration', 'release_year', 'tags']]

In [27]:
newdata['tags'] = newdata['tags'].apply(lambda x: " ".join(x))
newdata['tags'] = newdata['tags'].apply(lambda x: x.lower())

In [28]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [29]:
def stem(text):
  y = []
  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)

In [30]:
newdata['tags'] = newdata['tags'].apply(stem)

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [32]:
vectors = cv.fit_transform(newdata['tags']).toarray()

In [33]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [34]:
def recommend(movie):
  movie_index = newdata[newdata['title'] == movie].index[0]
  distances = similarity[movie_index]
  movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]
  for i in movies_list:
    print(newdata.iloc[i[0]].title)

In [35]:
newdata.sample()

,title,show_id,type,country,rating,duration,release_year,tags
3053,Win It All,s5541,Movie,United States,TV-MA,89 min,2017,joeswanberg jakejohnson aislinnderbez joelotru...

In [36]:
import pickle

In [37]:
pickle.dump(newdata,open('movies.pkl','wb'))

In [38]:
pickle.dump(newdata.to_dict(),open('movies_dict.pkl','wb'))

In [39]:
pickle.dump(similarity,open('similarity.pkl','wb'))