In [216]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [217]:
data = pd.read_csv('/content/netflix_titles.csv.zip')

<h1>1. Knowing My data</h1>

In [218]:
data.shape

(8807, 12)

In [219]:
data.head(2)['cast'].values

array([nan,
       'Ama Qamata, Khosi Ngema, Gail Mabalane, Thabang Molaba, Dillon Windvogel, Natasha Thahane, Arno Greeff, Xolile Tshabalala, Getmore Sithole, Cindy Mahlangu, Ryle De Morny, Greteli Fincham, Sello Maake Ka-Ncube, Odwa Gwanya, Mekaila Mathys, Sandi Schultz, Duane Williams, Shamilla Miller, Patrick Mofokeng'],
      dtype=object)

In [220]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [221]:
data.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [222]:
data.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [223]:
data.duplicated().sum()

np.int64(0)

In [224]:
data.corr(numeric_only=True)

              release_year
release_year           1.0

<h1>2. Univariate Analysis</h1>

In [225]:
# what columns we keep----> type, director, cast, country, rating, duration, listed_in, description, show_id, release_date

In [226]:
data = data[['title','type' , 'director','cast','country','rating','duration','listed_in','description','show_id','release_year']]

In [227]:
data.sample(5)

,title,type,director,cast,country,rating,duration,listed_in,description,show_id,release_year
5070,Love and Hong Kong,TV Show,NaN,"Eiko Koike, Ryo Yoshizawa, Fumika Baba, Moga M...",Japan,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...",The lives of five strangers become intertwined...,s5071,2017
8674,Viceroy's House,Movie,Gurinder Chadha,"Hugh Bonneville, Gillian Anderson, Manish Daya...","United Kingdom, India, Sweden",NR,106 min,Dramas,As viceroy Lord Mountbatten arrives in Delhi t...,s8675,2017
1425,Creating The Queen's Gambit,Movie,NaN,NaN,United States,TV-14,14 min,Documentaries,A fascinating character. Exquisite sets. A wig...,s1426,2021
3623,Enter the Anime,Movie,Alex Burunova,"Kozo Morishita, Yoko Takahashi, Shinji Aramaki...","United States, Japan",TV-MA,59 min,"Documentaries, International Movies",What is anime? Through deep-dives with notable...,s3624,2019
6265,Beauty and the Bitches,TV Show,NaN,"Methinee Kingpayome, Son Songpaisarn, Yingying...",NaN,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",Beauty pageant contestants from all over Thail...,s6266,2016

In [228]:
data.isnull().sum()

title              0
type               0
director        2634
cast             825
country          831
rating             4
duration           3
listed_in          0
description        0
show_id            0
release_year       0
dtype: int64

In [229]:
data = data.dropna().reset_index(drop=True)

In [230]:
data.isnull().sum()

title           0
type            0
director        0
cast            0
country         0
rating          0
duration        0
listed_in       0
description     0
show_id         0
release_year    0
dtype: int64

In [231]:
def convert(str):
  str = str.replace(" Movies", "")
  str = str.replace(" TV Shows", "")
  str = str.split(",")
  return str

In [232]:
data['listed_in'] = data['listed_in'].apply(convert)

In [233]:
data.head()

,title,type,director,cast,country,rating,duration,listed_in,description,show_id,release_year
0,Sankofa,Movie,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",TV-MA,125 min,"[Dramas, Independent, International]","On a photo shoot in Ghana, an American model s...",s8,1993
1,The Great British Baking Show,TV Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,TV-14,9 Seasons,"[British, Reality TV]",A talented batch of amateur bakers face off in...,s9,2021
2,The Starling,Movie,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,PG-13,104 min,"[Comedies, Dramas]",A woman adjusting to life after a loss contend...,s10,2021
3,Je Suis Karl,Movie,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic",TV-MA,127 min,"[Dramas, International]",After most of her family is murdered in a terr...,s13,2021
4,Jeans,Movie,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,TV-14,166 min,"[Comedies, International, Romantic]",When the father of the man she loves insists t...,s25,1998

In [234]:
def convertC(str):
  str = str.split(",")
  if len(str) >= 3:
    return str[:3]
  else:
    return str

In [235]:
data['cast'] = data['cast'].apply(convertC)

In [236]:
data['description'] = data['description'].apply(lambda x: x.split())

In [237]:
data['listed_in'] = data['listed_in'].apply(lambda x: [i.replace(" ", "") for i in x])
data['cast'] = data['cast'].apply(lambda x: [i.replace(" ", "") for i in x])
data['director'] = data['director'].apply(lambda x: ["".join(x)])

In [238]:
data['director'] = data['director'].apply(lambda x: [i.replace(" ", "") for i in x])

In [239]:
data['tags'] = data['director'] + data['cast'] + data['listed_in'] + data['description']

In [240]:
newdata = data[['title','show_id', 'type', 'country', 'rating', 'duration', 'release_year', 'tags']]

In [241]:
newdata['tags'] = newdata['tags'].apply(lambda x: " ".join(x))
newdata['tags'] = newdata['tags'].apply(lambda x: x.lower())

/tmp/ipykernel_5884/917672980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdata['tags'] = newdata['tags'].apply(lambda x: " ".join(x))
/tmp/ipykernel_5884/917672980.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdata['tags'] = newdata['tags'].apply(lambda x: x.lower())

In [242]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [243]:
def stem(text):
  y = []
  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)

In [244]:
newdata['tags'] = newdata['tags'].apply(stem)

/tmp/ipykernel_5884/2180838250.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdata['tags'] = newdata['tags'].apply(stem)

In [245]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [246]:
vectors = cv.fit_transform(newdata['tags']).toarray()

In [247]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [248]:
def recommend(movie):
  movie_index = newdata[newdata['title'] == movie].index[0]
  distances = similarity[movie_index]
  movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]
  for i in movies_list:
    print(newdata.iloc[i[0]].title)

In [249]:
newdata.sample()

,title,show_id,type,country,rating,duration,release_year,tags
1181,Aiyyaa,s2265,Movie,India,TV-14,151 min,2012,sachinkundalkar ranimukerji prithvirajsukumara...

In [250]:
import pickle

In [251]:
pickle.dump(newdata,open('movies.pkl','wb'))

In [252]:
pickle.dump(newdata.to_dict(),open('movies_dict.pkl','wb'))

In [253]:
pickle.dump(similarity,open('similarity.pkl','wb'))